<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Cat\cat40.png" />
    <None Remove="Assets\Cat\cat_atlas.png" />
    <None Remove="Assets\Cat\transparent_cat.png" />
    <None Remove="Assets\Dragon\Idle\idle_01.png" />
    <None Remove="Assets\Dragon\Idle\idle_02.png" />
    <None Remove="Assets\Dragon\Idle\idle_03.png" />
    <None Remove="Assets\Dragon\Idle\idle_04.png" />
    <None Remove="Assets\Dragon\Idle\idle_05.png" />
    <None Remove="Assets\Dragon\Idle\idle_06.png" />
    <None Remove="Assets\Dragon\Idle\idle_07.png" />
    <None Remove="Assets\Dragon\Idle\idle_08.png" />
    <None Remove="Assets\Dragon\Idle\idle_strip.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Cat\cat40.png" />
    <Resource Include="Assets\Cat\cat_atlas.png" />
    <Resource Include="Assets\Cat\transparent_cat.png" />
    <Resource Include="Assets\Dragon\Idle\idle_01.png" />
    <Resource Include="Assets\Dragon\Idle\idle_02.png" />
    <Resource Include="Assets\Dragon\Idle\idle_03.png" />
    <Resource Include="Assets\Dragon\Idle\idle_04.png" />
    <Resource Include="Assets\Dragon\Idle\idle_05.png" />
    <Resource Include="Assets\Dragon\Idle\idle_06.png" />
    <Resource Include="Assets\Dragon\Idle\idle_07.png" />
    <Resource Include="Assets\Dragon\Idle\idle_08.png" />
    <Resource Include="Assets\Dragon\Idle\idle_strip.png" />
  </ItemGroup>

</Project>
